### ISSUE TITLE
Mod conflict with aequivaleo

### ISSUE THREAD

**Issue by Cynix32** [Darkhax-Minecraft/Open-Loader#13]
Referencing ldtteam/Aequivaleo#20

When using openloader to load recipes and tags, aequivaleo tries to rescan again & again all the recipes and dimensions, which then causes the game to a halt, oftentimes leading to an OutofMemory error. As per my understanding of the dev of aequivaleo, this scanning of recipes and dimensions should only happen once per world, not everytime a world is loaded as in my case. But with loading recipes with openloader somehow breaks the game entirely.

However, loading openloader alone (without any resource or data packs in the openloader folder) with aequivaleo does not cause problems. The problem only specifically arises when there are datapacks and resourcepacks within openloader.

**Comment by Darkhax** [comment]
This mod does not modify any of the systems used by Aequivaleo, it only sideloads additional packs using the same method as Forge itself. My guess would be this issue is directly caused by some edge case in your custom datapacks and not OpenLoader itself. I am closing this issue here due to the link being improbable and your lack of response to https://github.com/ldtteam/Aequivaleo/issues/20. If further investigation do happen to uncover actual issues with my mod I will be happy to look into them.
