### ISSUE TITLE
Resourcepack selection ingame

### ISSUE THREAD

**Issue by vaporvee** [Darkhax-Minecraft/Open-Loader#18]
Maybe you could disable or add an option for it that you can't press the arrow down on a resourcepack ingame so that the resourcepack is always on top

<img src="https://vaporvee.com/bugscreenshots/vpm-bug1.png">

**Comment by vaporvee** [comment]
or completely hide it from the selection menu

**Comment by Darkhax** [comment]
Hello, thanks for the feedback and apologies for taking so long to reply to it. In the most recent version I have added the ability to prevent the pack from being moved around by players. This will do what you requested, however there are some limitations that can not be avoided. 

The first limitation is that the pack will be locked to the position it was at when the pack was first loaded. By default this will be at the top of the list, but as more packs are added they will be placed on top of the locked pack, pushing it to the middle. 

The second limitation is that packs below a locked pack in the list can not move above the locked pack, and packs above the locked list can not move below it. So if you have packs in the order of a,b,c,d,e and c is fixed in position, a and b can swap places, and d and e can as well, but you can not make d or e load before a or b. 

You can enable this potion by setting `"fixed_position": true` in the newly added packmeta file described [here](https://github.com/Darkhax-Minecraft/Open-Loader/issues/33#issuecomment-1987475364).
