### ISSUE TITLE
en_us language changes are not picked up on the server

### ISSUE THREAD

**Issue by Hubry** [Darkhax-Minecraft/Open-Loader#20]
We have a resource pack that replaces some advancement names - however while they show up on the clients correctly:

!["A fork in the road"](https://user-images.githubusercontent.com/26120076/154817241-b1013617-f6e6-4221-a997-ba2c1f88379e.png)

...Discord chat bridge mods use the translations from the server, and that's not loaded there: 

!["This is the Wae"](https://user-images.githubusercontent.com/26120076/154817255-a4e6edba-e7ce-4f20-93e1-7bfe3feaac81.png)

In case of modpacks adding new advancements purely with Open Loader, they show up like this:

![obraz](https://user-images.githubusercontent.com/26120076/154817287-927f8aa0-a4b3-4a59-a850-c6c7fe7270b7.png)

The top two screenshots are from an in-dev modpack for 1.18.1 made by a group of my friends, bottom screenshot is from Vazkii's patreon server running Crucial 2 (1.16.5).

**Comment by Darkhax** [comment]
After reviewing the code for server side localizations, I think the *right* way to achieve this is by including your language entries in a datapack as well. The Forge code appears to load language data from all data packs rather than just mods. So including the files in the assets file as you would with a mod should work fine.

It appears that Fabric API and QSL do not have analogous features and initializing my own resource manager for this sounds like a horrible idea. I think the best approach here would be to let them implement this feature.
