### ISSUE TITLE
1.16.5 compatibility about minecraft datapack

### ISSUE THREAD

**Issue by 2929762171** [Darkhax-Minecraft/Open-Loader#29]
I 'm playing a mod : RingsOfAscension-1.16.4-1.6.0,
then I found that I couldn't get any ring from the chest.
![U@8E(MSQN1N1G29VJZR4@KF](https://github.com/Darkhax-Minecraft/Open-Loader/assets/98941945/5b7aa5cc-756e-4443-8418-3b219708c728)
I change some animals entities loot tables for more meats, it worked in the OpenLoader, this means that the pack has no errors. but it caused the rings problem, just because the folder named "minecraft".
When I remove this minecraft folder, problem can be solved. But I do want to use it in the OpenLoader.
 
![B)HXPOWS @C9I}LN98E6G7K](https://github.com/Darkhax-Minecraft/Open-Loader/assets/98941945/427e7d13-53d3-448a-9ee3-94b5239916f0)
Maybe it's the special way it works that causes this problem.
Maybe other mods will have this problem.
![image](https://github.com/Darkhax-Minecraft/Open-Loader/assets/98941945/9bb4f93f-5b53-4a07-b7ab-829bc16c7f6e)

**Comment by 2929762171** [comment]
Loading sequence caused this problem.
Other mods had modified the data packet, but openloader always load at last, when I create a pack  of vanilla, it will reset the vanilla data, and destroyed other modules' modification of vanilla.

**Comment by Darkhax** [comment]
@2929762171 Are you including all of the vanilla datapack files in your custom data pack? This is unnecessary and will cause issues like the one you are having now. You should only include files you have actually modified. 

If you have intentionally edited the loot tables of chest loot for example, it is your responsibility to account for any changes mods may make. This is an intentional design choice by the Forge mod loader as they give user datapacks the final say on how loot tables are loaded.

**Comment by 2929762171** [comment]
I do have plans to edit other parts like chest loot table so I keep all of them, and that is why I want to use openloader to load it, only /reload is needed to test quickly...
I think it would be perfect if you could provide a  configuration about custom loading order.
Thanks for your reply.

**Comment by Darkhax** [comment]
It is not an issue with loading order. As I have already said Forge treats user defined packs as the definitive value for a loot table and will not allow mods to edit the results. You are explicitly telling Forge to ignore all mod related modifications to the loot table. This is not an issue with this mod or an issue I can fix, the fix is to only replace files you actually want to replace.
