### ISSUE TITLE
version 1 21 1

### ISSUE THREAD

**Issue by M0xiito** [Darkhax-Minecraft/Open-Loader#41]
### Question

and when will the mod switch to version 1 21 1?

**Comment by Darkhax** [comment]
You can find the 1.21.1 versions [here](https://www.curseforge.com/minecraft/mc-mods/open-loader/files/all?page=1&pageSize=20&version=1.21.1).

Please note that this update merges the data pack and resource pack folder into a single pack folder. This is because both pack types are now often deeply connected.
